# Site settings
title: Robyn Law
email: contact@robynlaw.online
description: "Hiya! Welcome to my website."
baseurl: "/" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author: Robyn Law
street_address:
city: Bromsgrove
state: West Midlands
zip_code:
country: United Kingdoms
phone:

icon: fa-cube # Font Awesome class for your site's icon

# Social settings
facebook_url:
github_url: https://github.com/Cinnabyn
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url: https://www.linkedin.com/in/robyn-law-baba66185/
pinterest_url:
slack_url: https://app.slack.com/client/T0383959N/D018QAZP4UU/user_profile/U0183D2T4QP
twitter_url: https://twitter.com/cinnabyn

# Build settings
markdown: kramdown

sass:
style: compressed
