# Site settings
title: Dimension
email: contact@robynlaw.online
description: A fully responsive site template designed by <a href="https://html5up.net">HTML5 UP</a> and released<br />for free under the <a href="https://html5up.net/license">Creative Commons</a> license.
baseurl: "/dimension-jekyll-theme" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author:
street_address: 
city: 
state: West Midlands
zip_code: 55555
country: United Kingdoms
phone: 

icon: fa-diamond # Font Awesome class for your site's icon

# Social settings
facebook_url:
github_url:
gitlab_url: 
googleplus_url: 
instagram_url:
linkedin_url: https://www.linkedin.com/in/robyn-law-baba66185/
pinterest_url:
slack_url:
twitter_url: https://twitter.com/cinnabyn

# Build settings
markdown: kramdown

sass:
style: compressed
